import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { DetectedSubscription } from '@/types';

export function exportToPDF(subscriptions: DetectedSubscription[]) {
  const doc = jsPDF();
  const today = new Date();
  const dateStr = today.toISOString().split('T')[0];
  const formattedDate = today.toLocaleDateString();

  // Header
  doc.setFontSize(20);
  doc.setTextColor(79, 70, 229); // Indigo
  doc.text('Substro — Subscription Report', 14, 22);
  
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139); // Slate 500
  doc.text(`Generated on ${formattedDate}`, 14, 30);

  const totalMonthly = subscriptions.reduce((sum, s) => sum + s.monthlyEstimate, 0);
  const totalAnnual = subscriptions.reduce((sum, s) => sum + s.annualEstimate, 0);

  // Summary Table
  autoTable(doc, {
    startY: 40,
    head: [['Total Subscriptions', 'Total Monthly', 'Total Annual']],
    body: [[subscriptions.length.toString(), `$${totalMonthly.toFixed(2)}`, `$${totalAnnual.toFixed(2)}`]],
    theme: 'plain',
    headStyles: { fillColor: [248, 250, 252], textColor: [100, 116, 139], fontStyle: 'bold' },
    styles: { fontSize: 12, cellPadding: 5 }
  });

  // Main Table
  autoTable(doc, {
    startY: (doc as any).lastAutoTable.finalY + 10,
    head: [['Merchant', 'Category', 'Monthly', 'Annual', 'Confidence']],
    body: subscriptions.map(s => [
      s.matchedMerchant?.name || s.cleanName,
      s.category,
      `$${s.monthlyEstimate.toFixed(2)}`,
      `$${s.annualEstimate.toFixed(2)}`,
      s.confidence.toUpperCase()
    ]),
    headStyles: { fillColor: [79, 70, 229], textColor: [255, 255, 255] },
    alternateRowStyles: { fillColor: [250, 250, 250] },
    styles: { fontSize: 10, cellPadding: 4 }
  });

  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184); // Slate 400
  doc.text('Generated by Substro · substro.app', 14, doc.internal.pageSize.getHeight() - 10);

  const filename = `Substro_Report_${dateStr}.pdf`;
  doc.save(filename);
}
